name: facebook/hermes/build

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      HERMES_WS_DIR: ${{ github.workspace }}
    steps:
      - name: Set up workspace and install dependencies
        run: |-
          yes | sdkmanager "cmake;3.22.1" &
          sudo apt update && sudo apt install -y libicu-dev
      - uses: actions/checkout@v4.1.0
        with:
          path: hermes
      - name: Build Hermes Compiler
        run: |-
          cmake -S hermes -B build
          # Build the Hermes compiler so that the cross compiler build can
          # access it to build the VM
          cmake --build ./build --target hermesc -j 4
      - name: Build Hermes for Android
        run: |-
          cd hermes/android
          ./gradlew githubRelease
      - name: Copy artifacts
        run: |-
          mkdir output
          cp build_android/distributions/hermes-runtime-android-*.tar.gz output
      - name: Checksum artifacts
        run: |-
          cd output
          for file in *
          do
            sha256sum "$file" > "$file.sha256"
          done
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: android-hermes
          path: output
  build-apple-runtime:
    runs-on: macos-latest
    env:
      TERM: dumb
      HERMES_WS_DIR: "/tmp/hermes"
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4
      - uses: actions/checkout@v4.1.0
      - name: Cache setup
        uses: actions/cache@v4.0.0
        with:
          key: v4-repo-${{ github.sha }}
          path: |-
            build_iphoneos
            build_catalyst
            build_iphonesimulator
            build_macosx
            destroot
      - name: Set up workspace
        run: mkdir -p /tmp/hermes/output
      - name: Install dependencies
        run: |-
          brew install cmake ninja
          sudo gem install cocoapods
      - name: Build the iOS frameworks
        run: "./utils/build-ios-framework.sh"
      - name: Build the Mac frameworks
        run: "./utils/build-mac-framework.sh"
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4
      - uses: actions/checkout@v4.1.0
        with:
          path: hermes
      - name: Install dependencies
        run: brew install cmake
      - name: Run MacOS regression tests in debug mode
        run: |-
          cmake -S hermes -B build -GXcode
          cmake --build ./build
          cmake --build ./build --target check-hermes
  test-apple-runtime:
    runs-on: macos-latest
    needs: build-apple-runtime
    env:
      TERM: dumb
      HERMES_WS_DIR: "/tmp/hermes"
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4
      - uses: actions/checkout@v4.1.0
      - name: Cache setup
        uses: actions/cache@v4.0.0
        with:
          key: v4-repo-${{ github.sha }}
          path: |-
            build_iphoneos
            build_catalyst
            build_iphonesimulator
            build_macosx
            destroot
      - name: Install dependencies
        run: brew install cmake ninja
      - name: Build the test application
        run: pod install
        working-directory: test/ApplePlatformsIntegrationTestApp
      - name: Test MacOS application
        run: |-
          xcodebuild test \
            -workspace ApplePlatformsIntegrationTests.xcworkspace \
            -configuration Debug \
            -destination 'platform=macOS' \
            -scheme ApplePlatformsIntegrationMacTests
        working-directory: test/ApplePlatformsIntegrationTestApp
      - name: Test iPhone application
        run: |-
          # Xcode 15 uses iOS 17 for simulator, and only iPhone 14/15 can work by
          # default, so use the oldest working model here.
          xcodebuild test \
            -workspace ApplePlatformsIntegrationTests.xcworkspace \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            -scheme ApplePlatformsIntegrationMobileTests
        working-directory: test/ApplePlatformsIntegrationTestApp
  package-apple-runtime:
    runs-on: macos-latest
    needs:
      - test-macos
      - test-apple-runtime
    env:
      TERM: dumb
      HERMES_WS_DIR: "/tmp/hermes"
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4
      - uses: actions/checkout@v4.1.0
      - name: Cache setup
        uses: actions/cache@v4.0.0
        with:
          key: v4-repo-${{ github.sha }}
          path: |-
            build_iphoneos
            build_catalyst
            build_iphonesimulator
            build_macosx
            destroot
      - name: Set up workspace
        run: mkdir -p /tmp/hermes/output
      - name: Install dependencies
        run: |-
          brew install cmake ninja
          sudo gem install cocoapods
      - name: Package the framework
        run: |-
          . ./utils/build-apple-framework.sh
          mkdir -p /tmp/cocoapods-package-root/destroot
          cp -R ./destroot /tmp/cocoapods-package-root
          cp hermes-engine.podspec LICENSE /tmp/cocoapods-package-root
          tar -C /tmp/cocoapods-package-root/ -czvf /tmp/hermes/output/hermes-runtime-darwin-v$(get_release_version).tar.gz .
      - name: Checksum artifacts
        run: |-
          cd /tmp/hermes/output
          for file in *
          do
            shasum -a 256 "$file" > "$file.sha256"
          done
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: apple-runtime
          path: /tmp/hermes/output/
  test-macos-test262:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4
      - uses: actions/checkout@v4.1.0
        with:
          path: hermes
      - name: Setup dependencies
        run: |-
          brew install cmake ninja
          # Check out test262 at a pinned revision to reduce flakiness
          git clone https://github.com/tc39/test262
          cd test262
          git checkout 19da3ca0757248f7595ee09d532bb83dd438f2b5
      - name: Run Hermes tests and test262 with Intl
        run: |-
          cmake -S hermes -B build -GNinja -DHERMES_ENABLE_INTL=ON
          cmake --build ./build
          cmake --build ./build --target check-hermes
          python3 hermes/utils/testsuite/run_testsuite.py --test-intl test262/test -b build/bin
